# fly.toml app configuration file generated for chatmd on 2023-05-25T17:21:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatmd"
primary_region = "mia"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
